// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

#import "AIOCryptoCore+Private.h"
#import "AIOCryptoCore.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface AIOCryptoCore ()

- (id)initWithCpp:(const std::shared_ptr<::crypto::core::api::CryptoCore>&)cppRef;

@end

@implementation AIOCryptoCore {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::crypto::core::api::CryptoCore>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::crypto::core::api::CryptoCore>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull NSString *)getStringVersion {
    try {
        auto objcpp_result_ = ::crypto::core::api::CryptoCore::getStringVersion();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

+ (int32_t)getIntVersion {
    try {
        auto objcpp_result_ = ::crypto::core::api::CryptoCore::getIntVersion();
        return ::djinni::I32::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto CryptoCore::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto CryptoCore::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<AIOCryptoCore>(cpp);
}

}  // namespace djinni_generated

@end
