// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#import "AIOGreetingDisplay+Private.h"
#import "AIOGreetingDisplay.h"
#import "AIOGreeting+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class GreetingDisplay::ObjcProxy final
: public ::crypto::core::api::GreetingDisplay
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::GreetingDisplay;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void display(const ::crypto::core::api::Greeting & c_greeting) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() display:(::djinni_generated::Greeting::fromCpp(c_greeting))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto GreetingDisplay::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto GreetingDisplay::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
