// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#import "AIOGreeting+Private.h"
#import "AIOGreetingColor+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Greeting::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.message),
            ::djinni::Enum<::crypto::core::api::GreetingColor, AIOGreetingColor>::toCpp(obj.color)};
}

auto Greeting::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[AIOGreeting alloc] initWithMessage:(::djinni::String::fromCpp(cpp.message))
                                          color:(::djinni::Enum<::crypto::core::api::GreetingColor, AIOGreetingColor>::fromCpp(cpp.color))];
}

}  // namespace djinni_generated
