// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace crypto
{
namespace core
{
namespace api
{

class GreetingDisplay;

class GreetingService
{
public:
    virtual ~GreetingService() {}

    /** Generating greetings is a lot of work */
    static constexpr int64_t COOLDOWN_MS = 4000;

    static std::shared_ptr<GreetingService> create_service(const std::shared_ptr<GreetingDisplay>& display);

    /** Call this in bg thread */
    virtual void greet(const std::vector<std::string>& who) = 0;
};

} // namespace api
} // namespace core
} // namespace crypto
