// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#include "greeting_service.hpp" // my header

namespace crypto { namespace core { namespace api {

int64_t constexpr GreetingService::COOLDOWN_MS;

}}} // namespace crypto::core::api
