// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#pragma once

#include "../../generated_api/greeting.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class Greeting final {
public:
    using CppType = ::crypto::core::api::Greeting;
    using JniType = jobject;

    using Boxed = Greeting;

    ~Greeting();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    Greeting();
    friend ::djinni::JniClass<Greeting>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("io/aetheras/djinni/Greeting") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Lio/aetheras/djinni/GreetingColor;)V") };
    const jfieldID field_mMessage { ::djinni::jniGetFieldID(clazz.get(), "mMessage", "Ljava/lang/String;") };
    const jfieldID field_mColor { ::djinni::jniGetFieldID(clazz.get(), "mColor", "Lio/aetheras/djinni/GreetingColor;") };
};

}  // namespace djinni_generated
