// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#pragma once

#include "../../generated_api/greeting_service.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class GreetingService final : ::djinni::JniInterface<::crypto::core::api::GreetingService, GreetingService> {
public:
    using CppType = std::shared_ptr<::crypto::core::api::GreetingService>;
    using CppOptType = std::shared_ptr<::crypto::core::api::GreetingService>;
    using JniType = jobject;

    using Boxed = GreetingService;

    ~GreetingService();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<GreetingService>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<GreetingService>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    GreetingService();
    friend ::djinni::JniClass<GreetingService>;
    friend ::djinni::JniInterface<::crypto::core::api::GreetingService, GreetingService>;

};

}  // namespace djinni_generated
