// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#include "greeting_display.hpp"  // my header
#include "greeting.hpp"

namespace djinni_generated {

GreetingDisplay::GreetingDisplay() : ::djinni::JniInterface<::crypto::core::api::GreetingDisplay, GreetingDisplay>() {}

GreetingDisplay::~GreetingDisplay() = default;

GreetingDisplay::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

GreetingDisplay::JavaProxy::~JavaProxy() = default;

void GreetingDisplay::JavaProxy::display(const ::crypto::core::api::Greeting & c_greeting) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::GreetingDisplay>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_display,
                           ::djinni::get(::djinni_generated::Greeting::fromCpp(jniEnv, c_greeting)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
