// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#import "AIOGreeting.h"


@implementation AIOGreeting

- (nonnull instancetype)initWithMessage:(nonnull NSString *)message
                                  color:(AIOGreetingColor)color
{
    if (self = [super init]) {
        _message = [message copy];
        _color = color;
    }
    return self;
}

+ (nonnull instancetype)greetingWithMessage:(nonnull NSString *)message
                                      color:(AIOGreetingColor)color
{
    return [(AIOGreeting*)[self alloc] initWithMessage:message
                                                 color:color];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p message:%@ color:%@>", self.class, (void *)self, self.message, @(self.color)];
}

@end
