// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#import "AIOGreeting.h"
#import <Foundation/Foundation.h>


@protocol AIOGreetingDisplay

- (void)display:(nonnull AIOGreeting *)greeting;

@end
