// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#import "AIOGreetingColor.h"
#import <Foundation/Foundation.h>

@interface AIOGreeting : NSObject
- (nonnull instancetype)initWithMessage:(nonnull NSString *)message
                                  color:(AIOGreetingColor)color;
+ (nonnull instancetype)greetingWithMessage:(nonnull NSString *)message
                                      color:(AIOGreetingColor)color;

@property (nonatomic, readonly, nonnull) NSString * message;

@property (nonatomic, readonly) AIOGreetingColor color;

@end
