// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#import <Foundation/Foundation.h>
@class AIOGreetingService;

/** Generating greetings is a lot of work */
extern int64_t const AIOGreetingServiceCooldownMs;

@interface AIOGreetingService : NSObject

+ (nullable AIOGreetingService *)createService;

/** Call this in bg thread */
- (nonnull NSString *)greet:(nonnull NSArray<NSString *> *)who;

@end
