// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

#import "AIOGreetingService+Private.h"
#import "AIOGreetingService.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface AIOGreetingService ()

- (id)initWithCpp:(const std::shared_ptr<::crypto::core::api::GreetingService>&)cppRef;

@end

@implementation AIOGreetingService {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::crypto::core::api::GreetingService>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::crypto::core::api::GreetingService>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable AIOGreetingService *)createService {
    try {
        auto objcpp_result_ = ::crypto::core::api::GreetingService::create_service();
        return ::djinni_generated::GreetingService::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)greet:(nonnull NSArray<NSString *> *)who {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->greet(::djinni::List<::djinni::String>::toCpp(who));
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}


namespace djinni_generated {

auto GreetingService::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto GreetingService::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<AIOGreetingService>(cpp);
}

}  // namespace djinni_generated

@end
