// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from core.djinni

package io.aetheras.djinni;

import java.util.concurrent.atomic.AtomicBoolean;

/**
 * @import "idl/example.djinni"
 * @import "idl/errors.djinni"
 */
public abstract class CryptoCore {
    /**
     * Gets the version of the library as a human readable string.
     * @return The version of the library (e.g. '1.0.1')
     */
    public static String getStringVersion()
    {
        return CppProxy.getStringVersion();
    }

    /**
     * Get the integer version of the Library
     * @return The integer version of the library
     */
    public static int getIntVersion()
    {
        return CppProxy.getIntVersion();
    }

    private static final class CppProxy extends CryptoCore
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        public static native String getStringVersion();

        public static native int getIntVersion();
    }
}
