// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

package io.aetheras.djinni;

public abstract class GreetingDisplay {
    public abstract void display(Greeting greeting);
}
