// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from greeting.djinni

package io.aetheras.djinni;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class GreetingService {
    /** Generating greetings is a lot of work */
    public static final long COOLDOWN_MS = 4000l;

    /** Call this in bg thread */
    public abstract String greet(ArrayList<String> who);

    public static GreetingService createService()
    {
        return CppProxy.createService();
    }

    private static final class CppProxy extends GreetingService
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public String greet(ArrayList<String> who)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_greet(this.nativeRef, who);
        }
        private native String native_greet(long _nativeRef, ArrayList<String> who);

        public static native GreetingService createService();
    }
}
